name: mgsc
channels:
    - conda-forge
    - defaults
dependencies:
    - python >= 3.6
    - pip
    - numpy
    - graphviz
    # version 1.3 gives me errors when accessing bounding boxes sometimes:
    # github.com/pygraphviz/pygraphviz/issues/113#issuecomment-298631567
    - pygraphviz >= 1.6
