# Based on
# https://github.com/fedarko/strainFlye/blob/main/.github/workflows/main.yml +
# https://github.com/biocore/empress/blob/master/.github/workflows/main.yml
name: MgSc JavaScript CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:

      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install MetagenomeScope's Node.js development dependencies
        run: npm install -g mocha-headless-chrome nyc prettier@2.0.5 jshint

      - name: Lint and stylecheck the JS code
        run: make jsstylecheck

      - name: Run JS tests
        run: make jstest

      - name: Upload JS code coverage information to Codecov
        uses: codecov/codecov-action@v2
