# Based on
# https://github.com/fedarko/strainFlye/blob/main/.github/workflows/main.yml
name: MgSc Python CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6]

    steps:

      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      - name: Check out code
        uses: actions/checkout@v3

      # https://github.com/conda-incubator/setup-miniconda#example-3-other-options
      - name: Install conda dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mgsc
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Install MetagenomeScope (and its pip dependencies)
        run: conda run -n mgsc pip install -e .[dev]

      - name: Lint and stylecheck the Python code
        run: conda run -n mgsc make pystylecheck

      - name: Run Python tests
        run: conda run -n strainflye make pytest

      - name: Upload Python code coverage information to Codecov
        uses: codecov/codecov-action@v2
